kind: flowservice
id: jsonplaceholderRest.flows.createPost
name: Create New Post
pipeline:
  - http.post:
      url: https://jsonplaceholder.typicode.com/posts
      headers:
        Content-Type: application/json
      body: "${request.body}"
    name: createPost
  - map:
      mappings:
        - expression: "${steps.createPost}"
          to: output
        - expression: 201
          to: output.statusCode
