kind: flowservice
id: jsonplaceholderRest.flows.createPost
name: Create New Post
pipeline:
  - service:
      id: common.services.http.post
      input:
        url: https://jsonplaceholder.typicode.com/posts
        headers:
          Content-Type: application/json
        body: "${request.body}"
    name: createPost
  - map:
      mappings:
        - expression: "${steps.createPost.body}"
          to: output.created
