kind: flowservice
id: jsonplaceholderWSDL.flows.convertNumber
name: Convert Number to Words via SOAP
pipeline:
  - soap.call:
      operation: NumberToWords
      input:
        bNum: "${request.body.number}"
    name: conversion
  - map:
      mappings:
        - expression: "${steps.conversion}"
          to: output.result
        - expression: "${request.body.number}"
          to: output.input_number
